
baseurl: "/github-io" # the subpath of your site, e.g. /blog

publications: True
#presentations: True
blog: True

title: Homepage of Jiajun Li
author: Jiajun Li
email: 522278689@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

#url: "https://git.coding.net/ljjwujun/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  llijiajun
exclude: [ppt_md/KMP.md]

theme_settings:
  title: Jiajun Li's Homepage

  experience_title: EXPERIENCE
  interests_title: RESEARCH INTERESTS
  skills_title: SKILLS
  #awards_title: AWARDS
  projects_title: PROJECTS
  recentpubs_title: RECENT PUBLICATIONS

paginate: 5
paginate_path: "blog/page:num"

sass:
  sass_dir:     _sass
  style:        compressed
plugins:
  - jekyll-scholar
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

bootstrap:
  assets: true

scholar:
  bibliography: _bibliography/publications.bib
  bibliography_template: pubstemplate
  style: apa
  locale: en
  last_name: Me
  first_name: [Myself, M.]
  sort_by: year,month
  order: descending,ascending
#  source: ./_bibliography/publications.bib
filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output



# Build settings
markdown: kramdown
theme: jekyll-theme-slate

# Gems
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-scholar
  # - jemoji #Uncomment this to allow emoji in your post

# Assets




# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5


academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
